# Generated by Django 5.0.1 on 2024-01-26 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('ID_Departement', models.AutoField(primary_key=True, serialize=False)),
                ('NomDepartement', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('ID_Person', models.AutoField(primary_key=True, serialize=False)),
                ('Nom', models.CharField(max_length=50)),
                ('Prenom', models.CharField(max_length=50)),
                ('DateNaissance', models.DateField(default='2000-01-01')),
                ('sexe', models.CharField(max_length=50)),
                ('Adresse', models.CharField(max_length=50)),
                ('num_tel', models.IntegerField(default=0)),
                ('email', models.EmailField(default='test@domain.com', max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Rendez_Vous',
            fields=[
                ('ID_RDV', models.AutoField(primary_key=True, serialize=False)),
                ('Date', models.DateField(default='2000-01-01')),
                ('Heure', models.TimeField(default='00:00:00')),
                ('Titre', models.CharField(default='Consultation', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Medecin',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='clinicHub.person')),
                ('ID_Medecin', models.AutoField(primary_key=True, serialize=False)),
                ('Departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinicHub.departement')),
            ],
            bases=('clinicHub.person',),
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='clinicHub.person')),
                ('ID_Patient', models.AutoField(primary_key=True, serialize=False)),
            ],
            bases=('clinicHub.person',),
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('ID_Observation', models.AutoField(primary_key=True, serialize=False)),
                ('Description', models.CharField(max_length=50)),
                ('Rendez_Vous', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinicHub.rendez_vous')),
            ],
        ),
        migrations.AddField(
            model_name='rendez_vous',
            name='Medecin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinicHub.medecin'),
        ),
        migrations.AddField(
            model_name='rendez_vous',
            name='Patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinicHub.patient'),
        ),
        migrations.CreateModel(
            name='ProcessusSpecific',
            fields=[
                ('ID_Processus', models.AutoField(primary_key=True, serialize=False)),
                ('Titre', models.CharField(max_length=50)),
                ('Description', models.CharField(max_length=250)),
                ('Medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinicHub.medecin')),
                ('Patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinicHub.patient')),
            ],
        ),
        migrations.CreateModel(
            name='DossierMedical',
            fields=[
                ('ID_Dossier', models.AutoField(primary_key=True, serialize=False)),
                ('DateCreation', models.DateField(auto_now_add=True, null=True)),
                ('Observations', models.ManyToManyField(blank=True, to='clinicHub.observation')),
                ('Patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinicHub.patient')),
            ],
        ),
    ]
