# Generated by Django 5.0.1 on 2024-01-26 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicHub', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processusspecific',
            name='Medecin',
        ),
        migrations.RemoveField(
            model_name='processusspecific',
            name='Patient',
        ),
        migrations.AddField(
            model_name='processusspecific',
            name='Departement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clinicHub.departement'),
        ),
    ]
