# Generated by Django 5.0.1 on 2024-01-28 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicHub', '0002_remove_processusspecific_medecin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dossiermedical',
            name='Patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clinicHub.patient'),
        ),
        migrations.AlterField(
            model_name='observation',
            name='Rendez_Vous',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clinicHub.rendez_vous'),
        ),
    ]
